---
apiVersion: v1
kind: Service
metadata:
  namespace: pihole
  name: pihole-svc-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole"
spec:
  selector:
    app: pihole
  ports:
  - name: pihole-admin
    port: 80
    targetPort: pihole-http
  - name: pihole-dns
    port: 53
    targetPort: dns
    protocol: TCP
  externalTrafficPolicy: Local
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  namespace: pihole
  name: pihole-svc-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole"
spec:
  selector:
    app: pihole
  ports:
  - name: dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
  externalTrafficPolicy: Local
  type: LoadBalancer
